### ISSUE TITLE
Crash when calling 'unregisterAudioFrameObserver'.

### ISSUE THREAD

**Issue by uzawa-gmo** [AgoraLibrary/flutter_agora_rtc_rawdata#5]
Wrong target to call in _channel.invokeMethod.

```dart
  static Future<void> unregisterAudioFrameObserver() {
    return _channel.invokeMethod('registerAudioFrameObserver');
  }
```
https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/blob/2d9b2ba0ea430150889d9a4547c76b4e92ad5890/lib/agora_rtc_rawdata.dart#L14

**Comment by LichKing-2234** [comment]
any crash log?

**Comment by uzawa-gmo** [comment]
@LichKing-2234 
I think it can be fixed by changing the '_channel.invokeMethod' of 'unregisterAudioFrameObserver()' to 'unregisterAudioFrameObserver'.

```
W/GENP.0  (11858): type=1400 audit(0.0:117794): avc: denied { search } for name="thermal" dev="sysfs" ino=35185 scontext=u:r:untrusted_app:s0:c192,c259,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.example.flutter_app
D/PipelineWatcher(11858): onInputBufferReleased: frameIndex not found (340); ignored
F/libc    (11858): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x72c483fa40 in tid 11858 (ple.flutter_app), pid 11858 (ple.flutter_app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sargo/sargo:11/RQ3A.210705.001/7380771:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2021-08-03 17:37:01+0900
pid: 11858, tid: 11858, name: ple.flutter_app  >>> com.example.flutter_app <<<
uid: 10960
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x72c483fa40
    x0  00000073a3083540  x1  0000000000000004  x2  0000007ff986d6a0  x3  0000007342a26118
    x4  0000007ff986d5b8  x5  0000000000000056  x6  4b4b484848484848  x7  7f7f7f7f7f7f7f7f
    x8  00000073a3083540  x9  00000072c483fa40  x10 0000000000000000  x11 0000000000000073
    x12 00000000000000a4  x13 0000007342d04b98  x14 0000000000000000  x15 0000007342a53e9f
    x16 00000072c4842c38  x17 00000072c4816064  x18 00000075d90c2000  x19 00000074b30697b0
    x20 0000000000000000  x21 00000074b30697b0  x22 00000075d86b0000  x23 00000074b3069868
    x24 00000073271bf168  x25 00000075d86b0000  x26 000000000000006e  x27 0000000000000003
    x28 0000007ff986d800  x29 0000007ff986d6b0
    lr  00000072c48160c0  sp  0000007ff986d670  pc  00000072c483fa40  pst 0000000060000000

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
_CallPageState.dispose failed to call super.dispose.

dispose() implementations must always call their superclass dispose() method, to ensure that all the resources used by the widget are fully released.
When the exception was thrown, this was the stack: 
#0      StatefulElement.unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:4804:7)
#1      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4811:6)
#2      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1847:13)
#3      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
#4      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
...
====================================================================================================
backtrace:
      #00 pc 000000000003ba40  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libcpp.so!libcpp.so (offset 0x3b000) (BuildId: 24035986b8040bd0ffbc0973742185b626ffb2d8)
      #01 pc 00000000000130bc  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libcpp.so (bool agora::util::AutoPtr<agora::media::IMediaEngine>::queryInterface<agora::rtc::IRtcEngine, agora::INTERFACE_ID_TYPE>(agora::rtc::IRtcEngine*, agora::INTERFACE_ID_TYPE)+88) (BuildId: 24035986b8040bd0ffbc0973742185b626ffb2d8)
      #02 pc 0000000000012c8c  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libcpp.so (agora::AudioFrameObserver::AudioFrameObserver(_JNIEnv*, _jobject*, long long)+528) (BuildId: 24035986b8040bd0ffbc0973742185b626ffb2d8)
      #03 pc 00000000000194d4  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libcpp.so (Java_io_agora_rtc_rawdata_base_IAudioFrameObserver_nativeRegisterAudioFrameObserver+80) (BuildId: 24035986b8040bd0ffbc0973742185b626ffb2d8)
      #04 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #05 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #06 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #07 pc 000000000031831c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #08 pc 000000000030e648  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #09 pc 000000000067ebc0  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #10 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #11 pc 00000000000013a4  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/base.apk!classes3.dex] (io.agora.rtc.rawdata.base.IAudioFrameObserver.registerAudioFrameObserver+20)
      #12 pc 000000000067c7e4  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #13 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #14 pc 0000000000000f92  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/base.apk!classes3.dex] (io.agora.agora_rtc_rawdata.AgoraRtcRawdataPlugin.onMethodCall+138)
      #15 pc 000000000067e21c  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #16 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #17 pc 0000000000154442  [anon:dalvik-classes.dex extracted in memory from /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/base.apk] (io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage+34)
      #18 pc 000000000067e21c  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #19 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #20 pc 000000000014a382  [anon:dalvik-classes.dex extracted in memory from /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/base.apk] (io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart+114)
      #21 pc 000000000067e21c  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #22 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #23 pc 000000000014903c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/base.apk] (io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage+8)
      #24 pc 0000000000305c44  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.6432830707213048161)+268) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #25 pc 000000000066b24c  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #26 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #27 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #28 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #29 pc 0000000000555028  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+468) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #30 pc 00000000005551c8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #31 pc 0000000000413d40  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+660) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #32 pc 0000000000379474  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+2512) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #33 pc 0000000000367524  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+72) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #34 pc 000000000132663c  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libflutter.so (BuildId: 137d09ab83a412ded1c33ef386351fcc0429a53b)
      #35 pc 0000000001326578  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libflutter.so (BuildId: 137d09ab83a412ded1c33ef386351fcc0429a53b)
      #36 pc 0000000001322408  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libflutter.so (BuildId: 137d09ab83a412ded1c33ef386351fcc0429a53b)
      #37 pc 000000000138428c  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libflutter.so (BuildId: 137d09ab83a412ded1c33ef386351fcc0429a53b)
      #38 pc 0000000001342568  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libflutter.so (BuildId: 137d09ab83a412ded1c33ef386351fcc0429a53b)
      #39 pc 00000000013476f8  /data/app/~~V87SwNBjdRP_WLCtlij3wQ==/com.example.flutter_app-G5N07IeYv9eNRPG4RLhRGQ==/lib/arm64/libflutter.so (BuildId: 137d09ab83a412ded1c33ef386351fcc0429a53b)
      #40 pc 0000000000019dac  /system/lib64/libutils.so (android::Looper::pollInner(int)+916) (BuildId: 5d6af74124211886d954d61c96514a46)
      #41 pc 00000000000199b0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: 5d6af74124211886d954d61c96514a46)
      #42 pc 0000000000110f80  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: 1dec5134a09522f9c83c48dae0aec3be)
      #43 pc 000000000020fc0c  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140) (BuildId: b04ecd89074e53f7f7197a64f9cad21f3cca1d09)
      #44 pc 000000000200159c  /memfd:jit-cache (deleted) (offset 0x2000000) (android.os.MessageQueue.next+204)
      #45 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #46 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #47 pc 000000000031831c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #48 pc 000000000030e648  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #49 pc 000000000067c544  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #50 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #51 pc 00000000003956fc  /system/framework/framework.jar (offset 0x91a000) (android.os.Looper.loop+156)
      #52 pc 0000000000305c44  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.6432830707213048161)+268) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #53 pc 000000000030dc34  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+200) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #54 pc 000000000030f01c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1772) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #55 pc 0000000000177f40  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*)+57848) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #56 pc 000000000013f7d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #57 pc 000000000019eda0  /system/framework/framework.jar (android.app.ActivityThread.main)
      #58 pc 0000000000305d4c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.6432830707213048161)+532) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #59 pc 000000000066b24c  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #60 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #61 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #62 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #63 pc 0000000000555748  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #64 pc 00000000004d4ef0  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #65 pc 00000000000896f4  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180) (BuildId: ceb5e62f6d91c45ea99526daec5879eba39c6a54)
      #66 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #67 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #68 pc 000000000031831c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #69 pc 000000000030e648  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #70 pc 000000000067c544  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #71 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #72 pc 000000000045a716  /system/framework/framework.jar (offset 0x1242000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #73 pc 0000000000305c44  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.6432830707213048161)+268) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #74 pc 000000000066b24c  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #75 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #76 pc 0000000000894708  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2280) (BuildId: b04ecd89074e53f7f7197a64f9cad21f3cca1d09)
      #77 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #78 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #79 pc 0000000000554184  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #80 pc 0000000000554638  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #81 pc 0000000000438b08  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+656) (BuildId: 0183cc6150704cdc371a87b659800e56)
      #82 pc 0000000000099424  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: 1dec5134a09522f9c83c48dae0aec3be)
      #83 pc 00000000000a08b0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+836) (BuildId: 1dec5134a09522f9c83c48dae0aec3be)
      #84 pc 0000000000003580  /system/bin/app_process64 (main+1336) (BuildId: 8b041fc279d5108900e48324bafa5142)
      #85 pc 000000000004988c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: 49090ae59e6ae37f8beae53c551820ad)
Lost connection to device.
```

**Comment by LichKing-2234** [comment]
Oh, It seems like a mistake. You can fix it on your fork repository.
